### ISSUE TITLE
Lowercase hex strings?

### ISSUE THREAD

**Issue by EthanRBrown** [kburdett/vim-nuuid#2]
I love this plugin!  So helpful.  However, I prefer lowercase GUIDs (`aaf86d45-ca42-4e07-abbc-3908723c7f99` rather than `AAF86D45-CA42-4E07-ABBC-3908723C7F99`).  Yes, I have first-world problems.

I took a look at the code and could not see for the life of me how it's ending up as uppercase to start with; if I run the Python directly in a REPL, it gives me lowercase values, so this must be some vim voodoo that's beyond me...if you can point me in the right direction, I'd be happy to submit a PR to add a global option (`g:nuuid_lowercase`?) to control this.  Thanks again for making my life way easier!

**Comment by kburdett** [comment]
So obviously this is a super late reply... but somebody has you covered :) give it a try

https://github.com/kburdett/vim-nuuid/pull/3
